### ISSUE TITLE
Lumia.Imaging.StorageFileImageSource' is not registered.

### ISSUE THREAD

**Issue by 78fede78** [Microsoft/lumia-imaging-quickstart#1]
I'm using a library of application windows phone 8.1

hello I have passed from version 2.0.184 to version 2.0.208 but I get this error:

ex  {System.TypeLoadException: Requested Windows Runtime type 'Lumia.Imaging.StorageFileImageSource' is not registered. ---> System.Runtime.InteropServices.COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   --- End of inner exception stack trace ---
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Lumia.Imaging.StorageFileImageSource..ctor(IStorageFile storageFile)
   at myCupid.CropPage.<BttonSalva_Click>d__9.MoveNext()}   System.Exception {System.TypeLoadException}

before my code worked perfectly

``` c#
 IRandomAccessStream fileStream = await _file.OpenAsync(Windows.Storage.FileAccessMode.Read);
BitmapImage bitmapImage = new BitmapImage();
WriteableBitmap wb = new WriteableBitmap((int)ContentPanel.Width, (int)ContentPanel.Height);
wb.SetSource(fileStream);
try
{
using (var filterEffect = new FilterEffect(new StorageFileImageSource(_file)))
```

**Comment by davidbozjak** [comment]
Hi,

Can you tell us more about what Visual Studio are you using, etc. We have seen this problem with using Visual Studio 2013 Update 4, and it has been fixed in the latest Update 5 which is currently in CTP.

There are a few workarounds avaliable, I think this is the easiest one if it just happens for that one class: https://social.msdn.microsoft.com/Forums/en-US/190923ca-f084-480b-aa89-96581fbc1ce6/lumiaimagingbufferproviderimagesource-is-not-registered-error-lumia-sdk?forum=wpdevelop

Or instead you could revert the Microsoft.Build.AppxPackage.dll to the version from Visual Studio 2013 Update 3. That fixes the problem and you do not need to do anything to the manifest files.

**Comment by 78fede78** [comment]
Hello David my version of visual studio is:

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

Do you think I can download?
http://www.microsoft.com/it-it/download/details.aspx?id=45910

**Comment by davidbozjak** [comment]
Yes, by downloading the Update 5 the problem should be gone! 

I recommend this course of action, but if you have a specific reason why you don't want to update to Update 5, there are some other workarounds, as I said above.

**Comment by 78fede78** [comment]
I managed to find previous versions of files and now it works.
https://onedrive.live.com/?cid=99b45ff02d12b84d&id=99B45FF02D12B84D%2160194&ithint=file,zip&authkey=!ACQoovyOLV-_7LQ

I'll update visual studio version 5 when it will be officially released by Microsoft. thank you very much.
